### ISSUE TITLE
Svelte Syntax Error

### ISSUE THREAD

**Issue by Demysdcl** [BuilderIO/jsx-lite#24]
```

<script>
  let showInput;
  let state = { name: "Steve" };
</script>

<style>
  .input-1 {
    color: red;
  }
</style>

<div>
  {#if showInput}
    <input class="input-1" bind:value={state.name} />
  {/if}

  Hello! I can run in React, Vue, Solid, or Liquid!
</div>

```

**Comment by mandx** [comment]
Hi @Demysdcl! Would you mind pointing us to the specific error location? I'm trying this very code in [Svelte's REPL](https://svelte.dev/repl) and it doesn't give me any errors...

**Comment by Demysdcl** [comment]
> Hi @Demysdcl, thanks for your interest in JSX-Lite! Would you mind pointing us to the specific error location? I'm trying this very code in [Svelte's REPL](https://svelte.dev/repl) and it doesn't give me any errors...

I put  the correct code, the example in your site has the error

**Comment by mandx** [comment]
Ah yes I see what you mean now.

Right now, JSX-Lite probably won't generate the most idiomatic code for each framework; right now it we are focusing on it generating working code. This doesn't mean however that JSX-Lite won't use Svelte `bind:`ings in the future, we do plan to improve code generation in general to use the target framework's features better.

**Comment by steve8708** [comment]
realized we can support auto compiling to bind:value when very easily detectable 

![ezgif com-gif-maker (6)](https://user-images.githubusercontent.com/844291/100699204-2e784900-334f-11eb-9b79-2132af00beed.gif)

added via https://github.com/BuilderIO/jsx-lite/commit/36bf691f1c773d192134bd943c38976704d95717

thanks for the feedback @Demysdcl
