### ISSUE TITLE
any plan to support compiling jsx to customElements class of web components?

### ISSUE THREAD

**Issue by uptonking** [BuilderIO/jsx-lite#34]
jsx-lite example

``` jsx
import { useState } from '@jsx-lite/core';

export default function MyComponent(props) {
  const state = useState({
    name: 'Steve'
  });

  return (
    <div>
      <Show when={props.showInput}>
        <input
          css={{ color: 'red' }}
          value={state.name}
          onChange={(event) => (state.name = event.target.value)}
        />
      </Show>
      Hello! I can run in React, Vue, Solid, or Liquid!
    </div>
  );
}
```
may be compiled to something like this

``` js
class MyComponent extends HTMLElement {
  constructor() {
    super();
	this.state = {
	name: 'Steve'
	}
  }

 connectedCallback() {
    this.innerHTML = `<div> <show> </show></div>;
  }

}

customElements.define('my-component', MyComponent});

```

web components is the official standard.   
It's becoming more and more popular for big companies, like [google polymer](https://github.com/Polymer/polymer), [microsoft fast](https://github.com/microsoft/fast),[salesforce lwc](https://github.com/salesforce/lwc), [SAP ui5](https://github.com/SAP/ui5-webcomponents)... 

implementation ideas may be inspired by project [react-to-webcomponent](https://github.com/bitovi/react-to-webcomponent)

**Comment by steve8708** [comment]
Great idea @uptonking - alpha support added!
