### ISSUE TITLE
vite-plugin-ssr

### ISSUE THREAD

**Issue by brillout** [BuilderIO/jsx-lite#64]
ryansolid told me that you may be interested in https://github.com/brillout/vite-plugin-ssr

For marketings sites, SSR is necessary and vite-plugin-ssr would allow you to generate SSR source code that is dev frienldy.

Hit me up on Discord if you have questions https://discord.gg/SUeuec9

**Comment by steve8708** [comment]
thanks @brillout , will do 👍
