### ISSUE TITLE
mitosis & react-gtk

### ISSUE THREAD

**Issue by ghost** [BuilderIO/jsx-lite#728]
Hi all! I was thinking of including **react-gtk** in **mitosis** for this. 

So... *What do you all think of this idea?* *Is it possible to write with **mitosis - gtk visual components to facilitate the creation of mockups, prototypes, webapps in a linux environment natively** ?*

**example**
```javascript
import React, { Component } from 'react';
import { render, Button, Box } from '@react-gtk/binding';

class App extends Component {
  render() {
    return (
      <Box>
        <Button label="One" />
        <Button label="Two" />
      </Box>
    );
  }
}

render(<App />, 'My App');
```

**Comment by samijaber** [comment]
Our docs on generators are not perfect yet, but take a look here: https://github.com/BuilderIO/mitosis/blob/main/developer/generators.md

I doubt we would add this to the codebase at this moment, but you're free to build your own custom `react-gtk` generator for your use-case!
