### ISSUE TITLE
web component in mitosis: Is it possible to create web components with mitosis?

### ISSUE THREAD

**Issue by ghost** [BuilderIO/jsx-lite#761]
Hi all.

I would like to know if it is possible to create web components with mitosis. *Is it possible to create web components with mitosis?*

<br/>

**Note:** *This is a question and not a feature request.*

**Comment by dezkareid** [comment]
Yes, You can include target web components. This is a [list](https://github.com/BuilderIO/mitosis/blob/main/packages/core/src/targets.ts) of all targets available for mistosis
