### ISSUE TITLE
add `onInit` hook support in Qwik generator

### ISSUE THREAD

**Issue by samijaber** [BuilderIO/jsx-lite#861]
Came out of this PR discussion: https://github.com/BuilderIO/mitosis/pull/855#issuecomment-1297496490

the Qwik generator needs to support the `onInit` mitosis hook, and its contents should be rendered within Qwik's `useMount$` hook.

How:

Essentially copy this logic: https://github.com/BuilderIO/mitosis/blob/084de1af31f1181772fd73dcbfd20382e1508d47/packages/core/src/generators/qwik/component-generator.ts#L151-L165

but replace `component.hooks.onMount.code` with `component.hooks.onInit.code`, and `useClientEffect$` with `useMount$`. That should be all!

**Comment by decadef20** [comment]
If possible, I will try it.

**Comment by samijaber** [comment]
Sounds good!
