### ISSUE TITLE
@emotion/react: Builder JSON conversion to React + Next.js

### ISSUE THREAD

**Issue by ffleandro** [BuilderIO/jsx-lite#88]
I'm trying to use a React generated Component in a Next.js application, generated from a Builder JSON object that was created through Figma + BuilderIO Plugin.

My conversion command:
```
jsx-lite compile --to=react --from=builder --out-dir=dist/ figma/MyComponent.json
```

This generates a React component that uses the `@emotion/react` library.

```
/** @jsx jsx */
import { jsx } from "@emotion/react";

export default function MyComponent(props) {
  return (...)
};
```

However, the generated react component uses some components like `Image`, `Columns` or `Column` objects and next.js isn't able to find them.

From the [emotionjs docs](https://emotion.sh/docs/ssr#nextjs) it says Next.js is supported out of the box without any changes required:
> For @emotion v10 and above, SSR just works in Next.js.

Should I manually edit the generated `MyComponent.jsx` file and correcly apply the imports or is there a configuration I'm missing in next.config.js or webpack configuration?

I've successfully changed the imports to look like this and fixed most of the issues, however I'm still having issues finding the correct import declarations for `Columns` and `Column` components:
```
/** @jsx jsx */ /** @jsxRuntime classic */
import { jsx } from '@emotion/react';
import Image from '@emotion/styled';
import React from 'react';

export default function MyComponent(props) {
  return (...)
};
```

**Comment by Dkendal** [comment]
Hey @ffleandro!

The `<Columns />`, `<Column />`, and `<Image />` components you mentioned are Builder specific react components that we have defined within the editor. These should only be included in the output if you're planning on letting Builder render the content as jsx-lite. These shouldn't have been included in the compiler output by default, so thanks for point that out :smile: !

Once the linked PR is merged, in version 1 and greater of @jsx-lite/cli this will no longer be the behavior and the custom elements will be replaced with standard HTML markup. To opt back in to this behavior you can use the new `--builder-components` flag.

For your components styles I would suggest using the `--styles=styled-jsx` flag, which will emit a `<style jsx> { ... }</style>` block which  is [supported by next.js
](https://nextjs.org/docs/basic-features/built-in-css-support#css-in-js)

This flag is poorly documented but only works for react, you can see the options available to it here: https://github.com/Dkendal/jsx-lite/blob/5af5e5b6c409e20d96f1fac7ca1f63594f46d231/packages/core/src/generators/react.ts#L39

Hopefully that helps, let me know if anything was unclear!
